Fix for NoSuchMethodError on calling removeLast() on mutableList in Android - mutableListOf<String>() returns a MutableList, which on Android is usually backed by java.util.ArrayList. - ArrayList does not have removeLast() in the Java implementation on Android (even though Kotlin defines an extension removeLast() for the JVM, it sometimes fails on older Android runtimes). - That’s why you get: java.lang.NoSuchMethodError: No interface method removeLast()... - but works well with desktop variant